# Generated by Django 2.1.2 on 2018-10-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_auto_20181002_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='remaining_budget',
            field=models.FloatField(default=0.0),
        ),
    ]
