# Generated by Django 2.1.2 on 2018-10-08 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_auto_20181003_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='budgets.Budget'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('WITHDRAWAL', 'Withdrawal'), ('DEPOSIT', 'Deposit')], default='WITHDRAWAL', max_length=16),
        ),
    ]
